### ISSUE TITLE
Original licence is changed?

### ISSUE THREAD

**Issue by JocaPC** [kevindb/jquery-load-json#18]
Hi Kevin,

Thanks for maintaining this component, I have found several exports of original source, but it seems that you are the only one who is fixing issues. I would like to help if possible.

There might be a licencing problem with your copy.
Licence of original code is dual (BSD or GPL) and you have retained this in the source code; however, you stated on project home that the licence is GPL. If you look at the original slte https://code.google.com/p/jquery-load-json/ you will see that primary licence is BSD (in the left side). 
The main difference is that with BSD people can use it in commercial software without need to make it GPL or to use other GLP components only. Primary BSD licence is chosen because we should not have any restriction.
It might be even better to change licence to MIT since it depends on jQuery, which is licensed under MIT licence. This might avoid any misunderstanding such as duality of licences.

Regards,
Jovan Popovic

**Comment by JocaPC** [comment]
jquery-load-json plugin is originally derived from Alexandre Caprais noTemplate plugin that has GNU Lesser General Public License. I'm not expert for changing licences, but maybe this licence should be used.

**Comment by kevindb** [comment]
First of all, thank you for your work on this library. It has made numerous projects of mine easier to write.

It's my (admittedly novice) understanding that redistributing BSD licensed code under the GPL is well-accepted as both legally and ethically acceptable. [[ref]](https://groups.drupal.org/node/14734)
That said, my intention in using the GPL was to ensure that the library would remain open source. Upon further research, I agree with you that the GPL is *too* restrictive in this case. The LGPL that Alexandre used seems to be the right balance.
