### ISSUE TITLE
Enhance to support hidden+checkboxes with identical name

### ISSUE THREAD

**Issue by charleslyk** [kevindb/jquery-load-json#19]
Hi Kevin, first of all, thank you for taking the effort to maintain this library.

I'm currently encountering a scenario where the library does not work.  In essence, when I have the following (for the purpose of having a default value instead of "" when no checkbox is selected aka Ms MVC checkbox), jquery-load-json does not work:

```
<input type="checkbox" name="PreferencePrimary" value="P1" />P1
<input type="checkbox" name="PreferencePrimary" value="P2" />P2
<input type="hidden" name="PreferencePrimary" value="XXX" />
```

To enhance the library to support this, I've made the following changes.

Add before line 274 (v1.3.1)

``` javascript
else if (element.length > 0 && element.filter('input:hidden').length > 0 && element.filter(':checkbox').length > 0) {
                    element.filter(':checkbox').each(function () {
                        setElementValue(this, obj, name);
                    });
                } else if (element.length > 0 && element[0].type == 'checkbox') {
```

And line 318-328 (v1.3.1)

``` javascript
var value = obj;
                var type;
                if (element.length > 0) {
                    if (element.filter('input:hidden').length > 0 && element.filter(':checkbox').length > 0) {
                        setElementValue(element.filter(':checkbox').first()[0], obj, name);
                    } else {
                        var i = 0;
                        for (i = 0; i < element.length; i++) {
                            setElementValue(element[i], obj, name);
                        }
                    }
                } else {
                    setElementValue(element, obj, name);
                }
```

Thanks! Please accept my thanks for reviewing the code and apologies if I'm not adhering to any protocol since I'm still pretty new to Github.

**Comment by kevindb** [comment]
Charles, thank you for your interest, I'm glad that loadJSON is helpful. The best way to contribute to projects on Github is by submitting a Pull Request, which is a programmatic way of submitting your code changes. Here are some articles on Pull Requests:
https://guides.github.com/activities/forking/
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/creating-a-pull-request/

This idea of using a hidden field to provide a default value for a series of checkboxes is entirely new to me. I have always used my server-side code (e.g. ColdFusion, PHP) that the form submits to to set a default value if my checkbox field is non-existent. Doesn't the hidden field method pose a problem if any of the checkboxes _are_ checked? Doesn't that mean that the form submission would include both your 'default' value _and_ any checked values, like this?
```
?PreferencePrimary=P1&PreferencePrimary=XXX
```

**Comment by charleslyk** [comment]
Hi Kevin,

I've submitted a pull request.  Please be gentle as this is my 1st pull request. :)

To answer your question, why this is done:

1) When the underlying data type is a nullable bool (tri-state : null, false, true) and we need to differentiate between checkbox not selected (false) in a GUI vs the value not being submitted (e.g REST call).

2) MVC.net automatically doing this. (http://stackoverflow.com/questions/2697299/asp-net-mvc-why-is-html-checkbox-generating-an-additional-hidden-input)

**Comment by kevindb** [comment]
Thank you for the PR, but I don't think this feature has enough widespread usefulness to merge into the plugin.
