### ISSUE TITLE
CDNJS

### ISSUE THREAD

**Issue by krheinwald** [kevindb/jquery-load-json#21]
Would you consider putting this on https://cdnjs.com ?

**Comment by kevindb** [comment]
I would love for this library to be on cdnjs! However, cdnjs has the following requirement:

> Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example

You can help by starring the repo and asking your friends to star as well. We're already 10% of the way there!

P.S. I now feel like a YouTube person, asking people to, "Remember to like and follow us below!"
