### ISSUE TITLE
Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by sheldon-sminq** [kevindb/jquery-load-json#23]
We use this plugin extensively, recently updated to the latest 1.3.3 version to support HTML5 elements too.

While loading the form with the json data if one of the properties has a null value then we get this issue. Never occurred with the older version.

```
Uncaught TypeError: Cannot read property 'constructor' of null
   at h (jquery.loadJSON.min.js:18)
   at h (jquery.loadJSON.min.js:18)
   at HTMLFormElement.<anonymous> (jquery.loadJSON.min.js:18)

```

**Comment by kevindb** [comment]
What specific version of the jQuery library you're using?
What browsers (and versions) have you tested in?
Please include a link to a [JSFiddle](https://jsfiddle.net/) or [CodePen](https://codepen.io/) example of the error so that others can reproduce the issue you're seeing.

**Comment by sheldon-sminq** [comment]
```
Jquery Version: 2.1.4
Browsers : Chrome 58.0.3029
https://jsfiddle.net/91715o1j/ sample test
```

**Comment by fvarg00** [comment]
Suggested fix for this issue under 

https://github.com/kevindb/jquery-load-json/pull/27/commits/341004c2a1ab0ac4273a19ddecc46c2900b86f9c
