### ISSUE TITLE
Patch for jquery.loadJSON.js version 1.2.5.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kevindb/jquery-load-json#7]
```
1.2.5.mod.1
-----------
    Removed unused mobile option
    Added option to avoid init method execution (to solve problem when used with other jQuery plugins -jQuery Form Plugin-)
    Added option to implement custom onSetValue method (so you can change default behavior for specific fields)
    Replaced $().attr("value", newVal) with $().val(newVal) (to solve problem when used with other jQuery plugins -jQuery Form Plugin-)

```

Original issue reported on code.google.com by `rubensa` on 24 Apr 2013 at 9:59

Attachments:
* [jquery.loadJSON-1.2.5-to-mod.1.patch](https://storage.googleapis.com/google-code-attachments/jquery-load-json/issue-7/comment-0/jquery.loadJSON-1.2.5-to-mod.1.patch)

**Comment by kevindb** [comment]
The init function does not seem to be in conflict with modern jQuery plugins. This issue can be reopened with an example.

Unless I'm misunderstanding its value, an onSetValue callback seems to be superseded by event listeners like onChange.
